import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Who from "@/components/Who";
import WhatSection from "@/components/WhatSection";
import ScrollToTop from "react-scroll-to-top";
import Rocket from "@/assets/scroll-top/Rocket.svg";
import How from "@/components/How";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Creative Planets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Who />
        <WhatSection />
        <How />
        <ScrollToTop
          smooth
          style={{
            background: "transparent",
            boxShadow: "none",
            right: "0",
            margin: "48px",
          }}
          component={
            <img src={Rocket.src} alt="scrollTop" width="52" height="131" />
          }
        />
      </main>
    </>
  );
}
