import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Button from '@/components/Button'
import Header from '@/components/Header'
import Who from '@/components/Who'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Creative Planets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Who />
        {/* <Button title="See more"></Button> */}
      </main>
    </>
  )
}
