import Head from "next/head";
import { useEffect } from "react";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Who from "@/components/Who";
import WhatSection from "@/components/WhatSection";
import Rocket from "@/assets/scroll-top/Rocket.svg";
import How from "@/components/How";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
  }, []);

  return (
    <>
      <Head>
        <title>Creative Planets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Who />
        <WhatSection />
        <How />
        <button
          className="fixed z-10 right-12 bottom-12"
          onClick={() => {
            window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
          }}
        >
          <img src={Rocket.src} alt="scroll-top" />
        </button>
        <Footer />
      </main>
    </>
  );
}
